backend:
  name: github
  repo: alexsteele110/gatsby-netlify

media_folder: static/assets

collections:
  - name: "project" # all the things in one entry, for documentation and quick testing
    label: "Project"
    folder: "blog"
    create: true
    fields:
      - label: "Project Title"
        searchFields: ["title", "body"]
        valueField: "title"
      - {label: "Path", name: "path"}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Content block"
        name: "content"
        widget: "list"
        fields:
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}
