backend:
  name: github
  repo: alexsteele110/gatsby-netlify

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }

  - name: "kitchenSink" # all the things in one entry, for documentation and quick testing
    label: "Kitchen Sink"
    folder: "sink"
    create: true
    fields:
      - label: "Project Title"
        name: "post"
        searchFields: ["title", "body"]
        valueField: "title"
      - {label: "Path", name: "path"}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Content block"
        name: "content"
        widget: "list"
        fields:
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
